---
default:
  tags:
    - devops

image: node:14-alpine

stages:
  - code_review
  - build
  - docker
  - deploy-front
    
# sonarqube-check:
#   stage: code_review
#   image: 
#     name: sonarsource/sonar-scanner-cli:latest
#     entrypoint: [""]
#   variables:
#     SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
#     GIT_DEPTH: "0"
#   cache:
#     key: "${CI_JOB_NAME}"
#     paths:
#       - .sonar/cache
#   script: 
#     - sonar-scanner
#   allow_failure: true


build-front:
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - dist/webapp/
  
build-docker-image:
  stage: docker
  image: docker
  script:
    - docker build -t ${IMAGENAME} -f Dockerfile dist/webapp 
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_TOKEN}
    - docker push ${IMAGENAME}
    - docker image rm ${IMAGENAME}

deploy-front:
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  stage: deploy-front
  script:
    - cp $KUBE_CONFIG ./config
    - kubectl apply --kubeconfig ./config -f front-ban-eola.k8s.granux.fr.yaml

variables:
  IMAGENAME : '${DOCKERHUB_USER}/front-ban'

cache:
  paths:
    - node_modules/
