- name: Make sure Docker Daemon is launched
  systemd:
    state: started
    name: docker

- name: Copy Front config file
  template:                 # Ansible template module
    src: "config.json.j2"      # This is template src i.e source location 
    dest: "/tmp/config.json"   # Destination of Remote host

- name: Pull frontend
  community.docker.docker_image:
    name: "{{ nginx_image }}"
    source: pull

- name: Start container Nginx with exposed port (BUT NOT START AT BOOT !!!)
  community.docker.docker_container:
    name: nginx-web
    image: "{{ nginx_image }}"
    state: started
    ports:
      - "8001:80" 
    volumes:
      - /tmp/config.json:/usr/share/nginx/html/assets/config.json
